
package com.lixuan.corejava2.ch9.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Warehouse", targetNamespace = "http://server.ch9.corejava2.lixuan.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Warehouse {


    /**
     * 
     * @param description
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrice", targetNamespace = "http://server.ch9.corejava2.lixuan.com/", className = "com.lixuan.corejava2.ch9.client.GetPrice")
    @ResponseWrapper(localName = "getPriceResponse", targetNamespace = "http://server.ch9.corejava2.lixuan.com/", className = "com.lixuan.corejava2.ch9.client.GetPriceResponse")
    @Action(input = "http://server.ch9.corejava2.lixuan.com/Warehouse/getPriceRequest", output = "http://server.ch9.corejava2.lixuan.com/Warehouse/getPriceResponse")
    public double getPrice(
        @WebParam(name = "description", targetNamespace = "")
        String description);

}
